name: 'Terraform Apply'

on:
  workflow_call:
    

jobs:
  terraform-apply:
    name: 'Terraform Apply'
 
    runs-on: ubuntu-latest
    if: needs.terraform-plan.outputs.tfplanExitCode == 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
